Update to actions/checkout@v4 and actions/upload-artifact@v4
It seems v3 fails with:

    Error: Missing download info for actions/upload-artifact@v3

Updating to v4 seems to fix this.